name: build

on:
  push:
    branches: [ "master" ]
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: fwilhe2/setup-kotlin@main
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 18
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file
          
      - name: Install NDK
        run: echo "y" | ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.11902837"
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      
      
      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3.4.2
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          arguments: assembleDebug
           


      - name: Build with Gradle
        run: ./gradlew <android:run> assembleDebug --stacktrace --debug
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        

        
      - name: Rename Apks
        run: |
          mv app/build/outputs/apk/default/debug/app-default-universal-debug.apk DPD-${{ github.ref_name }}-default-universal.apk
          mv app/build/outputs/apk/default/debug/app-default-arm64-v8a-debug.apk DPD-${{ github.ref_name }}-default-arm64-v8a.apk
          mv app/build/outputs/apk/default/debug/app-default-x86_64-debug.apk DPD-${{ github.ref_name }}-default-x86_64.apk
          mv app/build/outputs/apk/default/debug/app-default-armeabi-v7a-debug.apk DPD-${{ github.ref_name }}-default-armeabi-v7a.apk
          mv app/build/outputs/mapping/defaultdebug/mapping.txt DPD-${{ github.ref_name }}-default-mapping.txt
          mv app/build/outputs/native-debug-symbols/defaultdebug/native-debug-symbols.zip DPD-${{ github.ref_name }}-default-native-debug-symbols.zip
          mv app/build/outputs/apk/marshmallow/debug/app-marshmallow-universal-debug.apk DPD-${{ github.ref_name }}-marshmallow-universal.apk
          mv app/build/outputs/apk/marshmallow/debug/app-marshmallow-arm64-v8a-debug.apk DPD-${{ github.ref_name }}-marshmallow-arm64-v8a.apk
          mv app/build/outputs/apk/marshmallow/debug/app-marshmallow-x86_64-debug.apk DPD-${{ github.ref_name }}-marshmallow-x86_64.apk
          mv app/build/outputs/apk/marshmallow/debug/app-marshmallow-armeabi-v7a-debug.apk DPD-${{ github.ref_name }}-marshmallow-armeabi-v7a.apk
          mv app/build/outputs/mapping/marshmallowdebug/mapping.txt DPD-${{ github.ref_name }}-marshmallow-mapping.txt
          mv app/build/outputs/native-debug-symbols/marshmallowdebug/native-debug-symbols.zip DPD-${{ github.ref_name }}-marshmallow-native-debug-symbols.zip
      - name: Releases
        uses: softprops/action-gh-release@v2
        with:
          body: Bump Version
          files: |
            DPD-${{ github.ref_name }}-default-universal.apk
            DPD-${{ github.ref_name }}-default-arm64-v8a.apk
            DPD-${{ github.ref_name }}-default-x86_64.apk
            DPD-${{ github.ref_name }}-default-armeabi-v7a.apk
            DPD-${{ github.ref_name }}-default-mapping.txt
            DPD-${{ github.ref_name }}-default-native-debug-symbols.zip
            DPD-${{ github.ref_name }}-marshmallow-universal.apk
            DPD-${{ github.ref_name }}-marshmallow-arm64-v8a.apk
            DPD-${{ github.ref_name }}-marshmallow-x86_64.apk
            DPD-${{ github.ref_name }}-marshmallow-armeabi-v7a.apk
            DPD-${{ github.ref_name }}-marshmallow-mapping.txt
            DPD-${{ github.ref_name }}-marshmallow-native-debug-symbols.zip
